### ISSUE TITLE
JSON Schema for configuration

### ISSUE THREAD

**Issue by Jack-Works** [cevek/ttypescript#100]
It will be nice to merge ttypescript configuration into https://json.schemastore.org/tsconfig!

You can see `ts-node` has already merged their config into tsconfig definition so there're out-of-box editor support for them.

![](https://user-images.githubusercontent.com/5390719/88011553-2bbc4a80-cb4a-11ea-9fd3-b9d1b7ce0202.png)

**Comment by cevek** [comment]
I don't think we can change existing tsconfig schema, because it maintained by typescript team

**Comment by Jack-Works** [comment]
But ts-node did that, they are also third party...
