### ISSUE TITLE
How to build without running into the build issue currently on master?

### ISSUE THREAD

**Issue by TomasHubelbauer** [cevek/ttypescript#115]
Hi, I see `master` is currently failing:

> src/loadTypescript.ts(42,9): error TS2611: 'exports' is defined as a property in class 'Module', but is overridden here in 'TypeScriptModule' as an accessor.

I have the same issue locally:

```sh
cd ttypescript
npm install
npm run build
```

However, I also see the latest release on GitHub and NPM is in response to the commit which is failing. So it looks like you have found a way to build and release without running into this error. Do I need to use a specific version of TypeScript?

**Comment by cevek** [comment]
Fixed in 1.5.13
