### ISSUE TITLE
Is ttypescript dead?

### ISSUE THREAD

**Issue by dko-slapdash** [cevek/ttypescript#122]
Hi @cevek @nonara,

Been a happy users of ttypescript for almost 2 years. Decided to upgrade TS, and:

- Last commit almost a year ago.
- People report incompatibility with TS 4.3 (and I also see weird errors).
- Also, people say that they move to ts-patch and it works with the latest TS (the last commit there is several weeks ago).

What's the future of the project? Or, maybe, the entire industry of TS plugins in dying, and there is no alternative?

Thanks!

**Comment by nonara** [comment]
The industry won't die. Many projects rely on plugins, including my own. This repo seems not to be maintained anymore, unfortunately. I have access to ts-patch, but not here.

If @cevek wants to add me as a maintainer, I'd be glad to maintain this until I can rewrite and merge the two libraries into a more robust plugin architecture.

**Comment by nonara** [comment]
Given the issues with ttypescript and its unmaintained status and the current limitation with `ts-patch`, I think it's time to do the rewrite.

I've sketched out the design. Here are the highlights:

- Will not directly modify ts files (better for yarn)
- Will allow persistent alias overwriting (ie. can name the compiler `tsc` or something else, default is `tspc`)
- Supports *custom patches* which allow actual AST transformation of typescript libraries themselves, opening the door for packaged middleware
- Uses smart caching for core patch and custom patches applied to typescript modules (improves speed)
- Single plugin package can contain multiple before, after, afterDeclarations transformers + patches
- Will maintain support for current `ttypescript` style transformer packages

I've decided to keep the name for simplicity and visibility. So the rewrite will be housed in ts-patch v2.

You can follow updates here: https://github.com/nonara/ts-patch/discussions/40

**Comment by cevek** [comment]
Actually, I also thought that the library was already out of date and did not work, 😅 but after testing it on the latest versions of `ts`, it turned out that everything is working, the only thing that broke(warning) is some kind of incompatibility with the new version of node module system, but I fixed it, so now everything is in working order.

**Comment by craigphicks** [comment]
> Actually, I also thought that the library was already out of date and did not work, sweat_smile but after testing it on the latest versions of `ts`, it turned out that everything is working, the only thing that broke(warning) is some kind of incompatibility with the new version of node module system, but I fixed it, so now everything is in working order.

I can verify that I am using this package successfully with typescript 4.4/5 (not updated to 4.5 yet) for a few months.  However, I wasn't using it two years ago so I have no previous behavior to compare to.  One barrier that had to be overcome was that the plugin main entry was called repeatedly to engage a lower level of iteration (the transform) in the plugin.  Once I figured that out and put in a guard to initialize the plugin only once, all was well.   I couldn't find anything about that in the documentation.

Infrequent updating of a package isn't necessarily undesirable, it can be a sign of welcome stability.  

Having two separate available and independent approaches ,`ttypescript` and `ts-patch`, is a good thing. Eventually I may try to integrate with `ts-patch`as well.
