### ISSUE TITLE
`ttsc` is not working on TS 4.9

### ISSUE THREAD

**Issue by samchon** [cevek/ttypescript#134]
`ts-node -C ttypescript` works, but `ttsc` is not working. 

code transformation does not working.

**Comment by Smrtnyk** [comment]
It looks related to https://github.com/microsoft/TypeScript/issues/51542
probably not an issue of ttypescript

**Comment by DanielRosenwasser** [comment]
4.9.4 is now out FWIW

**Comment by samchon** [comment]
TS has been updated to 4.9.4, but transformation is not working yet.

**Comment by samchon** [comment]
@DanielRosenwasser May I ask you one thing?

Looking at code of this `ttypescript`, it transforms TS source code by replacing `ts.createProgram` function. But after TS 4.9 patch, the `transformed.createTransform` function never be called. Is there any criticial change on TS not to call the `createProgram` function?

https://github.com/cevek/ttypescript/blob/a81ff1744aa2e505273adbc0ef7d788237165720/packages/ttypescript/src/patchCreateProgram.ts#L32-L113

**Comment by nonara** [comment]
@samchon I'll take a look tomorrow and work it out.

**Comment by samchon** [comment]
@cevek I just analyzed what makes `ttypescript` broken for a while. Hope my analysis to be helpful.

----

I'd tried hard coding special editing on `tsc.js` of TS and succeeded to transforming by modifing `performCompilation` function to be exported function. However, the `performCompilation` function is not exported member, but an internal function of [executeCommandLine.ts](https://github.com/microsoft/TypeScript/blob/main/src/executeCommandLine/executeCommandLine.ts#L885) file.

Therefore, to fix this bug occured after TS 4.9 update, `ttypescript` should update not only `createProgram` file, but also `executeCommandLine` function too.

**Comment by nonara** [comment]
ts `4.9.4` support is added in [ts-patch](https://github.com/nonara/ts-patch) `v2.1.0`

**Comment by forinda** [comment]
> ts `4.9.4` support is added in [ts-patch](https://github.com/nonara/ts-patch) `v2.1.0`



> ts `4.9.4` support is added in [ts-patch](https://github.com/nonara/ts-patch) `v2.1.0`

So downgrading typescript from `^5.x.x` works 🎉

**Comment by abbaty48** [comment]
No solution yet for ts5, downgrading to 4 works

**Comment by nonara** [comment]
Latest ts-patch rc (beta) supports ts v5, and I added some functionality so you don't have to do anything major to migrate from ttypescript. Just install and use `tspc` instead of `ttsc`

Here's more detail:

- https://github.com/nonara/ts-patch/issues/93#issuecomment-1500795063
