### ISSUE TITLE
Feature Request: Allow the export of the program instead of the transformer

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [cevek/ttypescript#15]
I would really love to use `ttypescript`

But I'm using the awesome [ts-simple-ast](https://github.com/dsherret/ts-simple-ast) library to create a transformer and it creates the program for you. So you never in control of this code: 

````typescript 
export default function (program: ts.Program, pluginOptions: {}) {
    return (ctx: ts.TransformationContext) => {
        return (sourceFile: ts.SourceFile) => {
            return sourceFile;
        }
    }
}
````
So if you could do something like.

````typescript
export default function() : ts.Program {
      const program: ts.Program = doTsSimpleJsStuff();
      return program
}
````
that would work.

I believe putting a signature check somewhere  [here](https://github.com/cevek/ttypescript/blob/master/packages/ttypescript/src/patchCreateProgram.ts#L24]) would do the trick but the module resolution should happen earlier than [here](https://github.com/cevek/ttypescript/blob/master/packages/ttypescript/src/PluginCreator.ts#L197).

**Comment by marthinus-engelbrecht** [comment]
I'm open to doing a pull request.

**Comment by cevek** [comment]
Hi @marthinus-engelbrecht!
We don't create a `program` manually, we just patch original `ts.createProgram` to expose program into transformers. If you want your own program you need create it yourself in your transformer
```ts
export default function (_: {}, pluginOptions: {}) {
    const program: ts.Program = doTsSimpleJsStuff();
    return (ctx: ts.TransformationContext) => {
        return (sourceFile: ts.SourceFile) => {
            return sourceFile;
        }
    }
}
```

**Comment by zerkalica** [comment]
Try to import ttypescript before importing ts-simple-ast:

```js
import 'ttypescript'
import Project from 'ts-somple-ast'
```
```

**Comment by marthinus-engelbrecht** [comment]
Thanks, guys. Will try it out
