### ISSUE TITLE
ttsc missing compilerOptions

### ISSUE THREAD

**Issue by oleksandr-dakal** [cevek/ttypescript#17]
Try to use ttypescript, but get error:
`> rimraf es | ttsc -p tsconfig.json`
`[node_modules]\ttypescript\lib\patchCreateProgram.js:38`
`if (compilerOptions.configFilePath === undefined) {`

According to error it's seems problem with compilerOptions 
TypeError: Cannot read property 'configFilePath' of undefined

Issue reproducible with typescript@2.9.1 (Older 2.8 works ok)

**Comment by paranoidjk** [comment]
same problem here

**Comment by paranoidjk** [comment]
cc/ @cevek @zerkalica  Should ttypescript ask users lock typescript version? Since almost every time typescript release a minor version, our app break down

**Comment by zerkalica** [comment]
Just lock typescript version in your project. Ttypescript has no hard dependency on typescript.

**Comment by paranoidjk** [comment]
I think it do have peer dependency. since a paticular ttypescript can not gurantee work well on any typescript version, am i understand right ?

**Comment by cevek** [comment]
Fixed in ttypescript@1.4.5
