### ISSUE TITLE
require('ttypescript') use locally installed typescript, similar to `ttsc` wrapper

### ISSUE THREAD

**Issue by cspotcode** [cevek/ttypescript#20]
The CLI wrapper `ttsc` attempts to load and patch the locally installed version of Typescript, but `require('ttypescript')` does not.  Will you accept a PR to implement the same behavior for `require('ttypescript')`? (detecting locally installed typescript)

**Comment by cevek** [comment]
`require('ttypescript')` must use only current version of typescript from the same node_modules.
Else it won't work as you'll expect, because if you run your app from different folders - ttypescript will use different typescript versions.

But for `ttsc` this behavior is ok because it expect that you run this command in project directory and every project can have own version of typescript.

**Comment by cspotcode** [comment]
I'm asking for something roughly like this:

```
const opts = { basedir: __dirname + "/../.." };
const typescriptFileName = resolve.sync('typescript/lib/typescript', opts);
const ts = require(typescriptFileName);
```

Basically, don't use the process's cwd.  *Do* use node's module resolution behavior, but specifically avoid loading `ttypescript/node_modules/typescript`.

That way, I can `npm install typescript@some-version ttypescript` and ttypescript will use the typescript version I installed.

Will that work?

**Comment by cevek** [comment]
if you do `npm install typescript` the npm will install ttypescript and latest typescript to your node_modules. If in your project typescript have already installed then npm won't install local typescript into ttypescript. 
But this works only if you use typescript >= 2.7

So this `npm install typescript@2.8 ttypescript` works perfectly

**Comment by cspotcode** [comment]
Oh yeah, you're right.  The nested typescript installation I was seeing must have come from some yarn or npm quirk.  (I'm contributing to a third-party project whose scripts use a mix of yarn and npm for some reason)

**Comment by cevek** [comment]
So, can I close this issue?

**Comment by cspotcode** [comment]
Yes, thank you, all set.
