### ISSUE TITLE
declarations error

### ISSUE THREAD

**Issue by goloveychuk** [cevek/ttypescript#23]
I have 
node_modules/ttypescript/lib/typescript.d.ts:2:15 - error TS2502: 'ts' is referenced directly or indirectly in its own type annotation.  2 declare const ts: typeof ts;    
when importing 'ttypescript'.
Looks like declarations are incorrect.

**Comment by foisonocean** [comment]
same problem, any updates?

**Comment by cevek** [comment]
Fixed in ttypescript@1.5.5
