### ISSUE TITLE
Suggestion: include typescript-is in Examples of transformers

### ISSUE THREAD

**Issue by woutervh-** [cevek/ttypescript#24]
Hi there!

I've recently been working on a new project called [typescript-is](https://github.com/woutervh-/typescript-is).
Basically it generates run-time type-checks and it's using the transformer API.
Perhaps you'd like to include it in your list of examples of transformers?
🤞

**Comment by cevek** [comment]
It's done

**Comment by woutervh-** [comment]
Awesome, thanks
