### ISSUE TITLE
missing import in published declaration file

### ISSUE THREAD

**Issue by ajafff** [cevek/ttypescript#31]
lib/typescript.d.ts
```ts
/// <reference path="patchCreateProgram.d.ts" />
declare const TS: typeof ts;
export = TS;
```

Gives a compiler error `Cannot find name 'ts'.` and causes intellisense to not work.
Maybe you could use the newer `declare const TS: import('typescript');` syntax added in typescript@2.9

**Comment by cevek** [comment]
fixed
