### ISSUE TITLE
Can't use "type": "ls"

### ISSUE THREAD

**Issue by xiaoxiangmoe** [cevek/ttypescript#40]
see https://github.com/cevek/ttypescript/blob/4ee7113fb17140e21792d6d9a4233184dad07a8b/packages/ttypescript/src/patchCreateProgram.ts#L90

and 

https://github.com/cevek/ttypescript/blob/4ee7113fb17140e21792d6d9a4233184dad07a8b/packages/ttypescript/src/PluginCreator.ts#L86

**Comment by cevek** [comment]
The problem that `ls` in not possible to get from the program and I will remove it from config soon. Sorry
