### ISSUE TITLE
process.cwd() won't find peer dependency if located in other directory

### ISSUE THREAD

**Issue by alteredtastes** [cevek/ttypescript#49]
line 8 `/lib/tsc.js` assumes the peer typescript dependency is in same directory as where the process began. it would be great to have an optional arg for indicating where exactly the typescript peer dependency is.

When I `cd ./app` and run `ttsc`, ttsc can't find the peer dependency from ./build/node_modules
```
projects/
   tsconfig.base.json
   build/
        node_modules/typescript/
   app/
        tsconfig.json (extends tsconfig.base.json)
   admin/
        tsconfig.json (extends tsconfig.base.json)
   core/
        tsconfig.json (extends tsconfig.base.json)

```

**Comment by cevek** [comment]
You can install ttypescript near your typescript, don't use it from global node_modules

**Comment by cevek** [comment]
PR welcome
