### ISSUE TITLE
Expose program to custom transformers

### ISSUE THREAD

**Issue by SupernaviX** [cevek/ttypescript#5]
If custom transformers had access to the current Program, they would be able to use its [TypeChecker](https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L1714) to introspect on the types in the code being transformed. CustomTransformers with knowledge of the type system could have lots of interesting uses; e.g. using a specific decorator to mark blocks of code to be transformed, or auto-generating type guards from interfaces.

**Comment by cevek** [comment]
Yeah, I thought about that too. Will be implemented in the next version

**Comment by SupernaviX** [comment]
Would you accept a PR? It looks like it works on my machine if I patch `ts.createProgram`, and then patch the `emit` method on the program created by that.

**Comment by cevek** [comment]
Why do you want to patch `emit`? 
I've patched only `ts.createProgram`
Can you check my last commits are that working for you?

**Comment by SupernaviX** [comment]
Cool, it works!

I patched emit because I didn't want to hold onto a global value for "program", was afraid that the wrong transformers would get the wrong program.

**Comment by cevek** [comment]
Fixed.
 `globalProgram` - it was bad idea :)
Now it's patched only `createProgram` and `program.emit` instead of the `ts.emitFiles `

**Comment by kristianmandrup** [comment]
So how do we use this from VS Code?

**Comment by SupernaviX** [comment]
To compile projects with it, update your build command to point to ttsc instead of tsc.

To tell vscode specifically to use this instead of normal typescript engine, add `"typescript.tsdk": "node_modules\\ttypescript\\lib"` to your `settings.json`. That won't really do much though, since these are just compile-time transformations.

**Comment by kristianmandrup** [comment]
@SupernaviX Why is this not documented in the Readme? I think there should be a section for VSC configuration? Cheers!

**Comment by SupernaviX** [comment]
I don't think configuring VSC to use it actually affects anything, since the IDE doesn't care about what happens at compile time. No reason for users to go to the trouble of setting that up.

@cevek could you please publish the new version?

**Comment by cevek** [comment]
@SupernaviX Done

**Comment by kristianmandrup** [comment]
Thanks for adding [VS Code section in Readme](https://github.com/cevek/ttypescript#vc-code) :)

**Comment by SupernaviX** [comment]
ohhhhh didn't realize that you were compiling _through_ VSCode. My bad.

**Comment by kasbah** [comment]
I don't really understand why VSCode is being discussed on this issue about the program/typechecker being available in the transformer.

**Comment by cevek** [comment]
Exposed the `program` argument in 1.0.9
