### ISSUE TITLE
Usage with @zeit/next-typescript

### ISSUE THREAD

**Issue by raine** [cevek/ttypescript#56]
Hello. Any idea how to hook this into [`@zeit/next-typescript`](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript)?

Looking at the source code of `@zeit/next-typescript`, I'm not sure how the webpack configuration shown in the README.md could be applied there.

Thanks.

**Comment by cevek** [comment]
You can use https://github.com/nonara/ts-patch for this framework
