### ISSUE TITLE
Typescript transform paths deleting / not generating import in *.d.ts files?

### ISSUE THREAD

**Issue by oleersoy** [cevek/ttypescript#62]
Hi,

I'm looking into how to go about fixing this bug:
**https://github.com/LeDDGroup/typescript-transform-paths/issues/24**

Import declarations are being left off generated `*.d.ts` files.  Looking through the source code I think this is the relevant section that does the work, but I don't see why it would cause the import to be left off, so I was wondering if maybe you would have any additional pointers for me:

```
  function visit(node: ts.Node): ts.VisitResult<ts.Node> {
    if (
      resolver &&
      ts.isExportDeclaration(node) &&
      !node.exportClause &&
      !compilerOptions.isolatedModules &&
      !resolver.moduleExportsSomeValue(node.moduleSpecifier)
    ) {
      return undefined;
    }
    if (ts.isImportDeclaration(node)) {
      return unpathImportDeclaration(node);
    }
    if (ts.isExportDeclaration(node)) {
      return unpathExportDeclaration(node);
    }

    return ts.visitEachChild(node, visit, context);
  }
```

The above snippet is taken from this source file:

https://github.com/LeDDGroup/typescript-transform-paths/blob/master/src/index.ts

Thoughts?

TIA,
Ole

P.S. [Also asked for help on SO](https://stackoverflow.com/questions/56939544/typescript-transform-paths-deleting-not-generating-import-in-d-ts-files)

**Comment by oleersoy** [comment]
I noticed that imports for nodes that are implementation specific are not being generated / included by the build.  I wonder if the proper way to distinguish between nodes that should be included in `*.d.ts` files and which ones are not is clear.

**Comment by danielpza** [comment]
Actually @oleersoy the code is from typescript https://github.com/microsoft/TypeScript/blob/583edce6b0505e12a4627902147141661ca1b256/src/compiler/transformers/ts.ts#L3051, we just made small changes, related https://github.com/microsoft/TypeScript/issues/31446
