### ISSUE TITLE
Is `ts-node` a required dependency to use this module?

### ISSUE THREAD

**Issue by thetutlage** [cevek/ttypescript#63]
Up until `1.5.6`, I was able to use `ttypescript` without installing `ts-node` as a separate dependency. However, from `1.5.7` onwards, the `ttsc` command fails when `ts-node` is not installed.

I do see a commit that moves `ts-node` from dependencies list to peerDependencies list, but I am not sure why `ts-node` is required when I just want to compile the code using `ttsc`

**Comment by tbranyen** [comment]
peer-deps don't install by default. this allows you to control the version. its the right behavior. you'll need to version it alongside

**Comment by thetutlage** [comment]
I know how peer dependencies works. The main question was, why compiling code needs `ts-node`? Isn’t typescript alone enough

**Comment by cevek** [comment]
@thetutlage `ttypescript` uses `ts-node` because you can specify local project transformers written in typescript

**Comment by thetutlage** [comment]
Okay makes sense. I was just trying to understand the reason behind its usage.
