### ISSUE TITLE
ESLint 6 Compatibility

### ISSUE THREAD

**Issue by leereichardt** [cevek/ttypescript#64]
**Environment**

- ESLint version:	6.1.0
- ttypescript:	1.5.7

Upgrading to ESLint v6 shows warnings when installing:
`npm WARN ttypescript@1.5.7 requires a peer of ts-node@^8.0.2 but none is installed. You must install peer dependencies yourself.`

**Comment by cevek** [comment]
This warning comes from npm. You just need to install ts-node
