### ISSUE TITLE
Git URL is invalid

### ISSUE THREAD

**Issue by Js-Brecht** [cevek/ttypescript#65]
I just wanted to let you know that the Git URL for `ttypescript` is invalid.  Not really that big of a deal; still easy enough to find your repo.  I just keep running into it, because I wind up using `npm info` to open it.  Doing the search on Github pops it right up, or can erase most of the url (back to the parent repository) after navigating to the broken link.  I just prefer launching a URL straight from the command line if I can, and having that link in the `npm info` is rather useful. :slightly_smiling_face:

**Comment by cevek** [comment]
Thanks!
