### ISSUE TITLE
Can i use more than one transform-plugin?

### ISSUE THREAD

**Issue by viT-1** [cevek/ttypescript#67]
e.g.
typescript-transform-paths for resolving tsconfig > paths
and @zoltu/typescript-transformer-append-js-extension for preparing scripts for es6 browser loading

**Comment by viT-1** [comment]
I need this to solve problem with paths in [my project](https://github.com/viT-1/systemjs-ts-es6)
I want to use more standart way than hacking sources with gulp-replace

**Comment by cevek** [comment]
Yes, you can use many plugins
