### ISSUE TITLE
ttypescript with transform plugins

### ISSUE THREAD

**Issue by viT-1** [cevek/ttypescript#69]
1.5.7 is working and transformed paths (by command line `ttsc --project ./tsconfig.json`) with custom transformers (e.g. @zerollup/ts-transform-paths) but latest (2.5.2) is not

**Comment by MichalLytek** [comment]
Both `1.5.7` and `1.5.8` works for me with `--project` and `@zerollup/ts-transform-paths`. Only the newest plugin [1.7.4 doesn't work](https://github.com/zerkalica/zerollup/issues/18).

**Comment by cevek** [comment]
The problem on the ts-transforms-paths side
