### ISSUE TITLE
Incompatible with TypeScript 3.7

### ISSUE THREAD

**Issue by unstubbable** [cevek/ttypescript#70]
Apparently the signature of `ts.executeCommandLine` has been changed in TS 3.7 which breaks the implementation in [packages/ttypescript/src/tsc.ts](https://github.com/cevek/ttypescript/blob/master/packages/ttypescript/src/tsc.ts).

**Comment by cevek** [comment]
Fixed in ttypescript@1.5.8 
https://github.com/cevek/ttypescript/releases/tag/1.5.8

**Comment by unstubbable** [comment]
Awesome, thanks for the quick fix!

**Comment by CristianPi** [comment]
I don't know why, but with typescript 3.7.x (with 3.6.x it works) the ttsc command crash with:
`performCompilation(sys, reportDiagnostic, cb, __assign(__assign({}, commandLine), { options: commandLineOptions }));

ReferenceError: __assign is not defined
`

Do i need to change something?

I already have the package to 1.5.8
typescript 3.7.3
