### ISSUE TITLE
Transformers with TSX extensions are not compiled

### ISSUE THREAD

**Issue by madou** [cevek/ttypescript#78]
Hi! Love the tool.

I'm trying to use it with `ts-loader` and `ts-jest` with an uncompiled transformer written in typescript - but it doesn't get compiled by ts-node (with compiler set as `ttypescript`).

It's fine if I run `ttsc` though.

Any ideas?

```
/Users/mdougall/projects/css-in-js/src/ts-transformer.tsx:1
(function (exports, require, module, __filename, __dirname) { export { default } from './ts-transformer/index';
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

**Comment by cevek** [comment]
I've just checked ts-jest with uncompiled transformer - it works for me. 
Could you please provide your example project to investigate the issue?

**Comment by madou** [comment]
Sure no worries will make a branch for you in a bit, thanks for the quick
response!

**Comment by madou** [comment]
hi @cevek 

```sh
git clone git@github.com:compiled/css-in-js.git
git checkout use-uncompiled-transformer
yarn
yarn start # runs storybook with ts-loader
yarn test # runs jest with ts-jest
```

PR here https://github.com/compiled/css-in-js/pull/32

**Comment by cevek** [comment]
Thank you! 
I've found and fixed a bug with ts-node config which working only with `ts` extenstion but no `tsx`
Check out `ttypescript@1.5.9`

**Comment by madou** [comment]
sweet thanks @cevek! that does indeed fix my problem - interestingly it doesn't look like `esModuleInterop` option is flowing through though.

could it not be picking up all the tsconfig?

```
/Users/mdougall/projects/css-in-js/src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx:123
  const compiledCss = stylis(`.${className}`, cssToPassThroughCompiler);
                            ^
TypeError: stylis_1.default is not a function
    at Object.exports.visitJsxElementWithCssProp (/Users/mdougall/projects/css-in-js/src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx:123:29)
```

**Comment by cevek** [comment]
I've added esModuleInterop: true in ttypescript@1.5.10

> could it not be picking up all the tsconfig?

For the transformer files should be another tsconfig because they run on nodejs side and can be different from main project settings.
In plugin system is not always possible to read from file system, so it should be default config for transformers.
Maybe in future we will support custom tsconfig

Default config: 
```
target: 'ES2018',
jsx: 'react',
esModuleInterop: true,
module: 'commonjs',
```

**Comment by madou** [comment]
fantastic solves all my problems, thanks @cevek!

> For the transformer files should be another tsconfig because they run on nodejs side and can be different from main project settings.

yeah that makes sense when said out loud - TIL 😄 

thanks again!
