### ISSUE TITLE
Usable with babel-loader?

### ISSUE THREAD

**Issue by FFdhorkin** [cevek/ttypescript#85]
We're using webpack with babel-loader, rather than ts-loader. Is there a way to get ttypescript working in this use case? Babel doesn't seem to support any the hooks for ttypescript's hooks.

**Comment by cevek** [comment]
ttypescript is just enhanced typescript
If you are using babel to compile ts to js you, ttypescript cannot help you.
But babel has builtin support for transformers, so try to write some babel plugin https://babeljs.io/docs/en/plugins#plugin-development
but babel cannot get typescript types
